### ISSUE TITLE
Make a FREEZE module variable and not a global logic module variable

### ISSUE THREAD

**Issue by marechal-p** [DaedalusMDW/bge_keymapper_class#4]
https://github.com/DaedalusMDW/bge_keymapper_class/blob/442f8d960be6bfa5653757702c05a8e12f13a0da/Project/PY/settings.py#L32

I know the BGE is not flooded with so much packages that we will easily encounter namespace collisions, but still. The `logic.FREEZE` variable is something internal to your logic/module, and thus should be stored as a module variable.

This means writing something along:

```python
FREEZE = None

def function(controller):
    global FREEZE

    if FREEZE ...
```

Just trying to give advices. Feel free to defend your ways too :)

**Comment by DaedalusMDW** [comment]
good point, i have no care how this should be done.  your way makes more sense. i considered just making it a game property too.

thanks, i always value input.

btw, sorry for taking so long, for some reason i didnt get an email notice.  ill look into that.
